CREATE TABLE IF NOT EXISTS Users (
	user_id	INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	firstname VARCHAR(255) NOT NULL,
	lastname VARCHAR(255),
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	avatar VARCHAR(255),
	role ENUM ('admin', 'company', 'user') DEFAULT 'user',
	cv BLOB,
	description LONGTEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
