-- ================================================
-- JOBS SEED DATA (50 ROWS TOTAL FOR TESTING) WITH SPECIFIED SKILLS
-- ================================================

INSERT INTO Jobs (title, description, salary, location, remote, skills, contract, number_candidates, company_id) VALUES
('Full Stack Developer', 'Join Aurora to design, build, and maintain scalable web applications. Work with modern JS frameworks and cloud technologies.', 37000, 'Paris', 'Full-remote', 'Python,HTML,CSS,Javascript', 'CDI', 0, 1),
('Frontend Engineer', 'Aurora seeks a Frontend Engineer to create responsive web interfaces and enhance user experience across devices.', 39000, 'Paris', 'Hybride', 'ReactJS,HTML,CSS', 'Stage', 0, 1),
('Backend Developer', 'Aurora backend team is looking for developers to optimize server-side applications and database performance.', 40000, 'Paris', 'Présentiel', 'NodeJS,SQL', 'CDI', 0, 1),
('Full Stack Developer', 'Aurora requires Full Stack Developers to maintain internal tools and client-facing apps with cloud integration.', 38000, 'Paris', 'Full-remote', 'PHP,Javascript,SQL', 'CDI', 0, 1),
('Frontend Engineer', 'Aurora wants Frontend Engineers to develop interactive UI components with modern JS frameworks.', 39500, 'Paris', 'Hybride', 'Vue.JS,HTML,CSS', 'Stage', 0, 1),
('Backend Developer', 'Aurora backend engineers will build RESTful APIs and optimize database queries for high-load applications.', 41000, 'Paris', 'Présentiel', 'Java,SQL', 'CDD', 0, 1),
('Full Stack Developer', 'Aurora seeks developers for e-commerce and SaaS solutions using modern backend and frontend technologies.', 38500, 'Paris', 'Hybride', 'Python,Javascript,ReactJS', 'CDI', 0, 1),
('Frontend Engineer', 'Aurora Frontend team needs engineers to improve performance and implement design specifications.', 40000, 'Paris', 'Full-remote', 'ReactJS,Typescript', 'Stage', 0, 1),
('Backend Developer', 'Aurora backend team requires experts in microservices, cloud deployment, and database optimization.', 42000, 'Paris', 'Présentiel', 'NodeJS,SQL', 'CDI', 0, 1),
('Full Stack Developer', 'Aurora hiring Full Stack Developers to maintain scalable SaaS applications and internal tools.', 39000, 'Paris', 'Hybride', 'Ruby,Javascript', 'CDI', 0, 1),

('Full Stack Developer', 'Leon is seeking Full Stack Developers to build and maintain customer-facing applications.', 37000, 'Lyon', 'Full-remote', 'Python,NodeJS,ReactJS', 'CDI', 0, 2),
('Frontend Engineer', 'Leon Frontend team seeks engineers to optimize SPA performance and implement modern designs.', 39000, 'Lyon', 'Hybride', 'Vue.JS,HTML,CSS', 'Stage', 0, 2),
('Backend Developer', 'Leon requires backend developers for API development and database maintenance.', 40000, 'Lyon', 'Présentiel', 'Java,SQL', 'CDI', 0, 2),
('Full Stack Developer', 'Leon Full Stack team is expanding for e-commerce and SaaS projects using cloud technologies.', 38000, 'Lyon', 'Full-remote', 'PHP,Javascript,SQL', 'CDI', 0, 2),
('Frontend Engineer', 'Leon wants creative Frontend Engineers to implement modern UI components.', 39500, 'Lyon', 'Hybride', 'ReactJS,Typescript', 'Stage', 0, 2),
('Backend Developer', 'Leon backend engineers will optimize microservices and maintain server reliability.', 41000, 'Lyon', 'Présentiel', 'NodeJS,SQL', 'CDD', 0, 2),
('Full Stack Developer', 'Leon hiring Full Stack Developers to integrate new features in SaaS platforms.', 38500, 'Lyon', 'Hybride', 'Python,Javascript,ReactJS', 'CDI', 0, 2),
('Frontend Engineer', 'Leon Frontend position: create responsive web apps with focus on performance.', 40000, 'Lyon', 'Full-remote', 'HTML,CSS', 'Stage', 0, 2),
('Backend Developer', 'Leon backend team looking for engineers to maintain APIs and databases.', 42000, 'Lyon', 'Présentiel', 'Ruby,SQL', 'CDI', 0, 2),
('Full Stack Developer', 'Leon Full Stack Developers needed to support SaaS and e-commerce applications.', 39000, 'Lyon', 'Hybride', 'Go,Javascript', 'CDI', 0, 2),

('Full Stack Developer', 'Maya seeks Full Stack Developers for building internal and client-facing tools.', 37000, 'Marseille', 'Full-remote', 'Python,Javascript,NodeJS', 'CDI', 0, 3),
('Frontend Engineer', 'Maya Frontend Engineers will enhance UX and implement responsive designs.', 39000, 'Marseille', 'Hybride', 'ReactJS,HTML,CSS', 'Stage', 0, 3),
('Backend Developer', 'Maya backend developers to work on APIs, microservices, and cloud integration.', 40000, 'Marseille', 'Présentiel', 'Java,SQL', 'CDI', 0, 3),
('Full Stack Developer', 'Maya is hiring Full Stack Developers to maintain SaaS and internal tools.', 38000, 'Marseille', 'Full-remote', 'PHP,Javascript,SQL', 'CDI', 0, 3),
('Frontend Engineer', 'Maya Frontend Engineers to implement interactive UI components and SPA features.', 39500, 'Marseille', 'Hybride', 'Vue.JS,Typescript', 'Stage', 0, 3),
('Backend Developer', 'Maya backend team needs developers to build and maintain scalable APIs.', 41000, 'Marseille', 'Présentiel', 'NodeJS,SQL', 'CDD', 0, 3),
('Full Stack Developer', 'Maya hiring Full Stack Developers to improve SaaS and web application performance.', 38500, 'Marseille', 'Hybride', 'Python,Javascript,ReactJS', 'CDI', 0, 3),
('Frontend Engineer', 'Maya Frontend Engineers required for responsive web and mobile designs.', 40000, 'Marseille', 'Full-remote', 'HTML,CSS', 'Stage', 0, 3),
('Backend Developer', 'Maya backend engineers maintain APIs and optimize database queries.', 42000, 'Marseille', 'Présentiel', 'Ruby,SQL', 'CDI', 0, 3),
('Full Stack Developer', 'Maya Full Stack developers to implement cloud-integrated SaaS solutions.', 39000, 'Marseille', 'Hybride', 'Go,Javascript', 'CDI', 0, 3),

('Full Stack Developer', 'Ethan seeks Full Stack Developers to maintain and expand their e-commerce platform.', 37000, 'Lille', 'Full-remote', 'Python,NodeJS,ReactJS', 'CDI', 0, 4),
('Frontend Engineer', 'Ethan Frontend team needs engineers to implement SPA features and enhance UX.', 39000, 'Lille', 'Hybride', 'Vue.JS,HTML,CSS', 'Stage', 0, 4),
('Backend Developer', 'Ethan backend team looking for developers to maintain APIs and database systems.', 40000, 'Lille', 'Présentiel', 'Java,SQL', 'CDI', 0, 4),
('Full Stack Developer', 'Ethan hiring Full Stack Developers for SaaS and internal tools using cloud tech.', 38000, 'Lille', 'Full-remote', 'PHP,Javascript,SQL', 'CDI', 0, 4),
('Frontend Engineer', 'Ethan Frontend Engineers to develop responsive UI with modern JS frameworks.', 39500, 'Lille', 'Hybride', 'ReactJS,Typescript', 'Stage', 0, 4),
('Backend Developer', 'Ethan backend engineers required for optimizing server-side logic and database queries.', 41000, 'Lille', 'Présentiel', 'NodeJS,SQL', 'CDD', 0, 4),
('Full Stack Developer', 'Ethan Full Stack Developers needed to implement SaaS features and internal tools.', 38500, 'Lille', 'Hybride', 'Python,Javascript,ReactJS', 'CDI', 0, 4),
('Frontend Engineer', 'Ethan Frontend Engineers to optimize SPA performance and UX.', 40000, 'Lille', 'Full-remote', 'HTML,CSS', 'Stage', 0, 4),
('Backend Developer', 'Ethan backend team to build scalable APIs and maintain database performance.', 42000, 'Lille', 'Présentiel', 'Ruby,SQL', 'CDI', 0, 4),
('Full Stack Developer', 'Ethan hiring Full Stack Developers to manage SaaS applications and cloud tools.', 39000, 'Lille', 'Hybride', 'Go,Javascript', 'CDI', 0, 4),

('Full Stack Developer', 'Sophie seeks Full Stack Developers to build SaaS applications and internal tools.', 37000, 'Toulouse', 'Full-remote', 'Python,NodeJS,ReactJS', 'CDI', 0, 5),
('Frontend Engineer', 'Sophie Frontend team requires engineers to implement responsive SPA features.', 39000, 'Toulouse', 'Hybride', 'Vue.JS,HTML,CSS', 'Stage', 0, 5),
('Backend Developer', 'Sophie backend team needs developers for API and database optimization.', 40000, 'Toulouse', 'Présentiel', 'Java,SQL', 'CDI', 0, 5),
('Full Stack Developer', 'Sophie hiring Full Stack Developers to integrate cloud solutions in SaaS products.', 38000, 'Toulouse', 'Full-remote', 'PHP,Javascript,SQL', 'CDI', 0, 5),
('Frontend Engineer', 'Sophie Frontend Engineers to improve UX and performance on web applications.', 39500, 'Toulouse', 'Hybride', 'ReactJS,Typescript', 'Stage', 0, 5),
('Backend Developer', 'Sophie backend engineers required for API development and database maintenance.', 41000, 'Toulouse', 'Présentiel', 'NodeJS,SQL', 'CDD', 0, 5),
('Full Stack Developer', 'Sophie Full Stack Developers to manage SaaS solutions and internal tools.', 38500, 'Toulouse', 'Hybride', 'Python,Javascript,ReactJS', 'CDI', 0, 5),
('Frontend Engineer', 'Sophie Frontend team to implement interactive UI with modern frameworks.', 40000, 'Toulouse', 'Full-remote', 'HTML,CSS', 'Stage', 0, 5),
('Backend Developer', 'Sophie backend engineers to maintain APIs, microservices, and databases.', 42000, 'Toulouse', 'Présentiel', 'Ruby,SQL', 'CDI', 0, 5),
('Full Stack Developer', 'Sophie Full Stack Developers for building SaaS solutions with cloud integration.', 39000, 'Toulouse', 'Hybride', 'Go,Javascript', 'CDI', 0, 5);
